//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MOHAMED-PC\\SQLEXPRESS;Initial Catalog=ERP;Integrated Security=True")]
        public string ERPConnectionString {
            get {
                return ((string)(this["ERPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ERP;Integrated Security=True")]
        public string ERPConnectionString1 {
            get {
                return ((string)(this["ERPConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Supply;Persist Security Info=True;User ID=sa;Passwo" +
            "rd=123")]
        public string SupplyConnectionString {
            get {
                return ((string)(this["SupplyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=anbdb;Persist Security Info=True;User ID=sa;Passwor" +
            "d=123")]
        public string anbdbConnectionString {
            get {
                return ((string)(this["anbdbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=162.254.161.2;Initial Catalog=erp;Persist Security Info=True;User ID=" +
            "softtec;Password=m0502181968")]
        public string erpConnectionString2 {
            get {
                return ((string)(this["erpConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=94.97.104.109,7033;Initial Catalog=erp;Persist Security Info=True;Use" +
            "r ID=softtec;Password=m0502181968")]
        public string erpConnectionString3 {
            get {
                return ((string)(this["erpConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=23.91.117.86;Initial Catalog=erp;Persist Security Info=True;User ID=s" +
            "ofttec;Password=m0502181968")]
        public string erpConnectionString4 {
            get {
                return ((string)(this["erpConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=94.97.104.109,7033;Initial Catalog=erplog;Persist Security Info=True;" +
            "User ID=softtec;Password=m0502181968")]
        public string erplogConnectionString {
            get {
                return ((string)(this["erplogConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=94.97.104.109,7033;Initial Catalog=Apps;Persist Security Info=True;Us" +
            "er ID=softtec;Password=m0502181968")]
        public string AppsConnectionString {
            get {
                return ((string)(this["AppsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=94.97.104.109,7033;Initial Catalog=erp;Persist Security Info=True;Use" +
            "r ID=softtec")]
        public string erpConnectionString5 {
            get {
                return ((string)(this["erpConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=94.97.104.109,7033;Initial Catalog=erpTrans;Persist Security Info=Tru" +
            "e;User ID=softtec;Password=m0502181968")]
        public string erpTransConnectionString {
            get {
                return ((string)(this["erpTransConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.3.14;Initial Catalog=erp;Persist Security Info=True;User ID=s" +
            "ofttec;Password=m0502181968")]
        public string erpConnectionString6 {
            get {
                return ((string)(this["erpConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=37.216.234.222,7033;Initial Catalog=erp;Persist Security Info=True;Us" +
            "er ID=softtec;Password=m0502181968")]
        public string erpConnectionString7 {
            get {
                return ((string)(this["erpConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=37.216.234.222,7034;Initial Catalog=erp;Persist Security Info=True;Us" +
            "er ID=softtec;Password=m0502181968")]
        public string erpConnectionString8 {
            get {
                return ((string)(this["erpConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=37.216.234.222,7034;Initial Catalog=apps;Persist Security Info=True;U" +
            "ser ID=softtec;Password=m0502181968")]
        public string appsConnectionString1 {
            get {
                return ((string)(this["appsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=23.91.117.86;Initial Catalog=apps;Persist Security Info=True;User ID=" +
            "softtec;Password=m0502181968")]
        public string appsConnectionString2 {
            get {
                return ((string)(this["appsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=37.216.234.222,7034;Initial Catalog=erplog;Persist Security Info=True" +
            ";User ID=softtec;Password=m0502181968")]
        public string erplogConnectionString1 {
            get {
                return ((string)(this["erplogConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.3.14\\mssql;Initial Catalog=erp;Persist Security Info=True;Use" +
            "r ID=softtec;Password=m0502181968")]
        public string erpConnectionString9 {
            get {
                return ((string)(this["erpConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=198.38.93.83;Initial Catalog=erp;Persist Security Info=True;User ID=s" +
            "ofttec;Password=m0502181968")]
        public string erpConnectionString10 {
            get {
                return ((string)(this["erpConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=95.218.102.111,7033\\MSSQL;Initial Catalog=erp;Persist Security Info=T" +
            "rue;User ID=softtec;Password=m0502181968")]
        public string erpConnectionString11 {
            get {
                return ((string)(this["erpConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.10\\mssql;Initial Catalog=erp;Persist Security Info=True;U" +
            "ser ID=softtec;Password=m0502181968")]
        public string erpConnectionString12 {
            get {
                return ((string)(this["erpConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=naqelat.net,7033\\MSSQL;Initial Catalog=erp;Persist Security Info=True" +
            ";User ID=softtec;Password=m0502181968")]
        public string erpConnectionString13 {
            get {
                return ((string)(this["erpConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=naqelat.net,7033\\MSSQL;Initial Catalog=erpTrans;Persist Security Info" +
            "=True;User ID=softtec;Password=m0502181968")]
        public string erpTransConnectionString1 {
            get {
                return ((string)(this["erpTransConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=naqelat.net,7033\\MSSQL;Initial Catalog=erplog;Persist Security Info=T" +
            "rue;User ID=softtec;Password=m0502181968")]
        public string erplogConnectionString2 {
            get {
                return ((string)(this["erplogConnectionString2"]));
            }
        }
    }
}
