//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع المستخدمين.
        /// </summary>
        internal static string AllUsers {
            get {
                return ResourceManager.GetString("AllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفــرع:.
        /// </summary>
        internal static string AreaLoc {
            get {
                return ResourceManager.GetString("AreaLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body.
        /// </summary>
        internal static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع : .
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/eng.png.
        /// </summary>
        internal static string BtnLangImg {
            get {
                return ResourceManager.GetString("BtnLangImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيارات جاهزة للتسليم.
        /// </summary>
        internal static string CarsReady {
            get {
                return ResourceManager.GetString("CarsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحادثة.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [سجل المحادثات].
        /// </summary>
        internal static string ChatLog {
            get {
                return ResourceManager.GetString("ChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فحص تسليم و استلام.
        /// </summary>
        internal static string CheckList {
            get {
                return ResourceManager.GetString("CheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to container.
        /// </summary>
        internal static string container {
            get {
                return ResourceManager.GetString("container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متابعة عملاء.
        /// </summary>
        internal static string CustomerFollowUp {
            get {
                return ResourceManager.GetString("CustomerFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير يومية.
        /// </summary>
        internal static string DailyReports {
            get {
                return ResourceManager.GetString("DailyReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات:.
        /// </summary>
        internal static string DataLoc {
            get {
                return ResourceManager.GetString("DataLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        internal static string dir1 {
            get {
                return ResourceManager.GetString("dir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string dir2 {
            get {
                return ResourceManager.GetString("dir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-align: right; position: absolute; color: White; font-family: Arial (Arabic);padding-right:5px;.
        /// </summary>
        internal static string DivCompany {
            get {
                return ResourceManager.GetString("DivCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float: left; font-family: Arial (Arabic); font-size: 14px;padding-left:5px;font-size: 14px;margin: 5px 0 0 10px;.
        /// </summary>
        internal static string DivLangStyle {
            get {
                return ResourceManager.GetString("DivLangStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شئون إدارية.
        /// </summary>
        internal static string EmpSys {
            get {
                return ResourceManager.GetString("EmpSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات الالكترونية.
        /// </summary>
        internal static string eServices {
            get {
                return ResourceManager.GetString("eServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمات الكترونية.
        /// </summary>
        internal static string eSys {
            get {
                return ResourceManager.GetString("eSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الأصناف.
        /// </summary>
        internal static string F1 {
            get {
                return ResourceManager.GetString("F1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة الصنف.
        /// </summary>
        internal static string F2 {
            get {
                return ResourceManager.GetString("F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخدمات.
        /// </summary>
        internal static string F3 {
            get {
                return ResourceManager.GetString("F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللون.
        /// </summary>
        internal static string F4 {
            get {
                return ResourceManager.GetString("F4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاس.
        /// </summary>
        internal static string F5 {
            get {
                return ResourceManager.GetString("F5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحجم.
        /// </summary>
        internal static string F6 {
            get {
                return ResourceManager.GetString("F6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلد المنشأ.
        /// </summary>
        internal static string F7 {
            get {
                return ResourceManager.GetString("F7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوحدات.
        /// </summary>
        internal static string F8 {
            get {
                return ResourceManager.GetString("F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخازن.
        /// </summary>
        internal static string F9 {
            get {
                return ResourceManager.GetString("F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string FDate {
            get {
                return ResourceManager.GetString("FDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الملفات.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متابعة رسائل الوصول.
        /// </summary>
        internal static string FollowSMS {
            get {
                return ResourceManager.GetString("FollowSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات متابعة.
        /// </summary>
        internal static string FollowUpOrder {
            get {
                return ResourceManager.GetString("FollowUpOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع حقوق الطبع و النسخ محفوظة.
        /// </summary>
        internal static string footer {
            get {
                return ResourceManager.GetString("footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة الناقلات البرية - 2018.
        /// </summary>
        internal static string footer1 {
            get {
                return ResourceManager.GetString("footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات العامة.
        /// </summary>
        internal static string GSetting {
            get {
                return ResourceManager.GetString("GSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة الناقلات البرية.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header.
        /// </summary>
        internal static string HeaderClass {
            get {
                return ResourceManager.GetString("HeaderClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة العامة.
        /// </summary>
        internal static string HeadOffice {
            get {
                return ResourceManager.GetString("HeadOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشئون الإدارية.
        /// </summary>
        internal static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستعلام.
        /// </summary>
        internal static string Inquery {
            get {
                return ResourceManager.GetString("Inquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرصدة أول الفترة.
        /// </summary>
        internal static string L1 {
            get {
                return ResourceManager.GetString("L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب شراء مستلزمات.
        /// </summary>
        internal static string L2 {
            get {
                return ResourceManager.GetString("L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-GB.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float: left;margin-top:6px; margin-left:-18px; font-family: Arial (Arabic); font-size: 14px;margin: 5px 0 0 10px;.
        /// </summary>
        internal static string LangDivStyle {
            get {
                return ResourceManager.GetString("LangDivStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangMsg {
            get {
                return ResourceManager.GetString("LangMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاحنات قادمة.
        /// </summary>
        internal static string li0001 {
            get {
                return ResourceManager.GetString("li0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاحنات في التحميل.
        /// </summary>
        internal static string li0002 {
            get {
                return ResourceManager.GetString("li0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاحنات مغادرة.
        /// </summary>
        internal static string li0003 {
            get {
                return ResourceManager.GetString("li0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيارات في الساحة.
        /// </summary>
        internal static string li0004 {
            get {
                return ResourceManager.GetString("li0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الرحلات.
        /// </summary>
        internal static string li0005 {
            get {
                return ResourceManager.GetString("li0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيارة جاهزة للتسليم.
        /// </summary>
        internal static string li0006 {
            get {
                return ResourceManager.GetString("li0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        internal static string li001 {
            get {
                return ResourceManager.GetString("li001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاقرار الضريبي.
        /// </summary>
        internal static string li04090 {
            get {
                return ResourceManager.GetString("li04090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة تسعير الغاز.
        /// </summary>
        internal static string li0949 {
            get {
                return ResourceManager.GetString("li0949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان مصروفات نثرية.
        /// </summary>
        internal static string li09849 {
            get {
                return ResourceManager.GetString("li09849", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحضور والانصراف.
        /// </summary>
        internal static string li104 {
            get {
                return ResourceManager.GetString("li104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        internal static string li110 {
            get {
                return ResourceManager.GetString("li110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        internal static string li12 {
            get {
                return ResourceManager.GetString("li12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنبيهات الشاحنات.
        /// </summary>
        internal static string li13 {
            get {
                return ResourceManager.GetString("li13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصادقة رصيد حساب.
        /// </summary>
        internal static string li14 {
            get {
                return ResourceManager.GetString("li14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجماليات الرواتب.
        /// </summary>
        internal static string li16 {
            get {
                return ResourceManager.GetString("li16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقييم مراكز الفروع.
        /// </summary>
        internal static string li17 {
            get {
                return ResourceManager.GetString("li17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايرادات و مصروفات الفرع.
        /// </summary>
        internal static string li18 {
            get {
                return ResourceManager.GetString("li18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الاساسية.
        /// </summary>
        internal static string li19 {
            get {
                return ResourceManager.GetString("li19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الشاحنات.
        /// </summary>
        internal static string li20 {
            get {
                return ResourceManager.GetString("li20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواقع الفروع.
        /// </summary>
        internal static string li21 {
            get {
                return ResourceManager.GetString("li21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البوابة الالكترونية.
        /// </summary>
        internal static string li22 {
            get {
                return ResourceManager.GetString("li22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستحقات الموظفين.
        /// </summary>
        internal static string li23 {
            get {
                return ResourceManager.GetString("li23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رواتب البنك.
        /// </summary>
        internal static string li24 {
            get {
                return ResourceManager.GetString("li24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متابعة رسائل الوصول.
        /// </summary>
        internal static string li25 {
            get {
                return ResourceManager.GetString("li25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور وأنصراف شهري.
        /// </summary>
        internal static string li26 {
            get {
                return ResourceManager.GetString("li26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود الدورية.
        /// </summary>
        internal static string li27 {
            get {
                return ResourceManager.GetString("li27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات صرف لم تستعاض.
        /// </summary>
        internal static string li272 {
            get {
                return ResourceManager.GetString("li272", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان ترحيل لم يصرف.
        /// </summary>
        internal static string li282 {
            get {
                return ResourceManager.GetString("li282", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتفاقية شحن طرود.
        /// </summary>
        internal static string li31 {
            get {
                return ResourceManager.GetString("li31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلبات شراء بدون أوامر.
        /// </summary>
        internal static string li32 {
            get {
                return ResourceManager.GetString("li32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتفاقية شحن بضاعة.
        /// </summary>
        internal static string li34 {
            get {
                return ResourceManager.GetString("li34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة مياه.
        /// </summary>
        internal static string li3449 {
            get {
                return ResourceManager.GetString("li3449", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة تسعير مياه.
        /// </summary>
        internal static string li349 {
            get {
                return ResourceManager.GetString("li349", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض سعر.
        /// </summary>
        internal static string li35 {
            get {
                return ResourceManager.GetString("li35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة العملاء.
        /// </summary>
        internal static string li36 {
            get {
                return ResourceManager.GetString("li36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الشاحنات.
        /// </summary>
        internal static string li37 {
            get {
                return ResourceManager.GetString("li37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلاغ حادث.
        /// </summary>
        internal static string li40 {
            get {
                return ResourceManager.GetString("li40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سائقين متعاونين.
        /// </summary>
        internal static string li4009 {
            get {
                return ResourceManager.GetString("li4009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان مصرفات نثرية.
        /// </summary>
        internal static string li4049 {
            get {
                return ResourceManager.GetString("li4049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلاغ حادث.
        /// </summary>
        internal static string li41 {
            get {
                return ResourceManager.GetString("li41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحكم بالاسطول.
        /// </summary>
        internal static string li4109 {
            get {
                return ResourceManager.GetString("li4109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل أوامر التشغيل.
        /// </summary>
        internal static string li42 {
            get {
                return ResourceManager.GetString("li42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤثرات الرواتب.
        /// </summary>
        internal static string li42349 {
            get {
                return ResourceManager.GetString("li42349", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل سندات الصرف.
        /// </summary>
        internal static string li43 {
            get {
                return ResourceManager.GetString("li43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايرادات والمصروفات.
        /// </summary>
        internal static string li4329 {
            get {
                return ResourceManager.GetString("li4329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحليل تكلفة قطع الغيار.
        /// </summary>
        internal static string li44 {
            get {
                return ResourceManager.GetString("li44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعدادات التطبيق.
        /// </summary>
        internal static string li44329 {
            get {
                return ResourceManager.GetString("li44329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الفواتير المغلقة.
        /// </summary>
        internal static string li449 {
            get {
                return ResourceManager.GetString("li449", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تتبع قطع الغيار.
        /// </summary>
        internal static string li45 {
            get {
                return ResourceManager.GetString("li45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان تسليم للفرع.
        /// </summary>
        internal static string li45590 {
            get {
                return ResourceManager.GetString("li45590", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوامر شراء بدون استلام.
        /// </summary>
        internal static string li45649 {
            get {
                return ResourceManager.GetString("li45649", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أستيراد البيانات.
        /// </summary>
        internal static string li456789 {
            get {
                return ResourceManager.GetString("li456789", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أصلاح خارجي سريع.
        /// </summary>
        internal static string li46 {
            get {
                return ResourceManager.GetString("li46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أصلاح خارجي سريع.
        /// </summary>
        internal static string li47 {
            get {
                return ResourceManager.GetString("li47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدمي الاجهزة الذكية.
        /// </summary>
        internal static string li48 {
            get {
                return ResourceManager.GetString("li48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان التجميع.
        /// </summary>
        internal static string li4900 {
            get {
                return ResourceManager.GetString("li4900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان التوزيع.
        /// </summary>
        internal static string li49000 {
            get {
                return ResourceManager.GetString("li49000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string li5 {
            get {
                return ResourceManager.GetString("li5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتفاقية خدمات الطريق.
        /// </summary>
        internal static string li50 {
            get {
                return ResourceManager.GetString("li50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة الغاز.
        /// </summary>
        internal static string li51 {
            get {
                return ResourceManager.GetString("li51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستندات وعقود.
        /// </summary>
        internal static string li7 {
            get {
                return ResourceManager.GetString("li7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعدادات البيانات.
        /// </summary>
        internal static string li749 {
            get {
                return ResourceManager.GetString("li749", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الحسابات.
        /// </summary>
        internal static string liA1 {
            get {
                return ResourceManager.GetString("liA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات الرئيسية.
        /// </summary>
        internal static string liA10 {
            get {
                return ResourceManager.GetString("liA10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحسابات التحليلية.
        /// </summary>
        internal static string liA11 {
            get {
                return ResourceManager.GetString("liA11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراكز الحسابات.
        /// </summary>
        internal static string liA12 {
            get {
                return ResourceManager.GetString("liA12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        internal static string liA13 {
            get {
                return ResourceManager.GetString("liA13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشاريع.
        /// </summary>
        internal static string liA14 {
            get {
                return ResourceManager.GetString("liA14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المناطق.
        /// </summary>
        internal static string liA15 {
            get {
                return ResourceManager.GetString("liA15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابات التكاليف.
        /// </summary>
        internal static string liA16 {
            get {
                return ResourceManager.GetString("liA16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملات.
        /// </summary>
        internal static string liA17 {
            get {
                return ResourceManager.GetString("liA17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموعات العمل.
        /// </summary>
        internal static string liA18 {
            get {
                return ResourceManager.GetString("liA18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدمين.
        /// </summary>
        internal static string liA19 {
            get {
                return ResourceManager.GetString("liA19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات القبض.
        /// </summary>
        internal static string liA24 {
            get {
                return ResourceManager.GetString("liA24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند صرف شيك.
        /// </summary>
        internal static string liA25 {
            get {
                return ResourceManager.GetString("liA25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيود اليومية.
        /// </summary>
        internal static string liA26 {
            get {
                return ResourceManager.GetString("liA26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسيمة إيداع بنكي.
        /// </summary>
        internal static string liA27 {
            get {
                return ResourceManager.GetString("liA27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحويلات بنكية.
        /// </summary>
        internal static string liA28 {
            get {
                return ResourceManager.GetString("liA28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب شراء مواد.
        /// </summary>
        internal static string liA29 {
            get {
                return ResourceManager.GetString("liA29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب دفع.
        /// </summary>
        internal static string liA30 {
            get {
                return ResourceManager.GetString("liA30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المطالبة المالية.
        /// </summary>
        internal static string liA31 {
            get {
                return ResourceManager.GetString("liA31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعدادات النظام.
        /// </summary>
        internal static string liA35 {
            get {
                return ResourceManager.GetString("liA35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطابقة الأرصدة.
        /// </summary>
        internal static string liA36 {
            get {
                return ResourceManager.GetString("liA36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشغيل قيود الاهلاك.
        /// </summary>
        internal static string liA37 {
            get {
                return ResourceManager.GetString("liA37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقفال الفترة.
        /// </summary>
        internal static string liA38 {
            get {
                return ResourceManager.GetString("liA38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دليل الحسابات.
        /// </summary>
        internal static string liA40 {
            get {
                return ResourceManager.GetString("liA40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف حساب تفصيلي.
        /// </summary>
        internal static string liA41 {
            get {
                return ResourceManager.GetString("liA41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر قيود اليومية.
        /// </summary>
        internal static string liA42 {
            get {
                return ResourceManager.GetString("liA42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف الاصول الثابتة.
        /// </summary>
        internal static string liA43 {
            get {
                return ResourceManager.GetString("liA43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحركة الشهرية للحسابات.
        /// </summary>
        internal static string liA44 {
            get {
                return ResourceManager.GetString("liA44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفتر الاستاذ.
        /// </summary>
        internal static string liA45 {
            get {
                return ResourceManager.GetString("liA45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميزان المراجعة.
        /// </summary>
        internal static string liA46 {
            get {
                return ResourceManager.GetString("liA46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف متابعة المستخدمين.
        /// </summary>
        internal static string liA47 {
            get {
                return ResourceManager.GetString("liA47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الدخل.
        /// </summary>
        internal static string liA60 {
            get {
                return ResourceManager.GetString("liA60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الميزانية العمومية.
        /// </summary>
        internal static string liA61 {
            get {
                return ResourceManager.GetString("liA61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة تسلسل السندات.
        /// </summary>
        internal static string liA62 {
            get {
                return ResourceManager.GetString("liA62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان أعمار الديون.
        /// </summary>
        internal static string liA63 {
            get {
                return ResourceManager.GetString("liA63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة صنف - التطبيق.
        /// </summary>
        internal static string liApp49 {
            get {
                return ResourceManager.GetString("liApp49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بطاقة خدمة - التطبيق.
        /// </summary>
        internal static string liApp51 {
            get {
                return ResourceManager.GetString("liApp51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة التسعير 2.
        /// </summary>
        internal static string liB09849 {
            get {
                return ResourceManager.GetString("liB09849", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التشغيل.
        /// </summary>
        internal static string liB1 {
            get {
                return ResourceManager.GetString("liB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدن.
        /// </summary>
        internal static string liB10 {
            get {
                return ResourceManager.GetString("liB10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع السيارات.
        /// </summary>
        internal static string liB11 {
            get {
                return ResourceManager.GetString("liB11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستويات التسعير.
        /// </summary>
        internal static string liB12 {
            get {
                return ResourceManager.GetString("liB12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سياسة التسعير.
        /// </summary>
        internal static string liB13 {
            get {
                return ResourceManager.GetString("liB13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العروض والمواسم.
        /// </summary>
        internal static string liB14 {
            get {
                return ResourceManager.GetString("liB14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        internal static string liB15 {
            get {
                return ResourceManager.GetString("liB15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السائقين.
        /// </summary>
        internal static string liB16 {
            get {
                return ResourceManager.GetString("liB16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاكواد العامة.
        /// </summary>
        internal static string liB17 {
            get {
                return ResourceManager.GetString("liB17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشاحنات.
        /// </summary>
        internal static string liB18 {
            get {
                return ResourceManager.GetString("liB18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع المركبات.
        /// </summary>
        internal static string liB19 {
            get {
                return ResourceManager.GetString("liB19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أتفاقية شحن - فاتورة.
        /// </summary>
        internal static string liB20 {
            get {
                return ResourceManager.GetString("liB20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الترحيل.
        /// </summary>
        internal static string liB21 {
            get {
                return ResourceManager.GetString("liB21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الوصول.
        /// </summary>
        internal static string liB22 {
            get {
                return ResourceManager.GetString("liB22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند أستلام سياره.
        /// </summary>
        internal static string liB23 {
            get {
                return ResourceManager.GetString("liB23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند قبض.
        /// </summary>
        internal static string liB24 {
            get {
                return ResourceManager.GetString("liB24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند صرف.
        /// </summary>
        internal static string liB25 {
            get {
                return ResourceManager.GetString("liB25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قسيمة إيداع بنكي.
        /// </summary>
        internal static string liB26 {
            get {
                return ResourceManager.GetString("liB26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب شراء مواد.
        /// </summary>
        internal static string liB27 {
            get {
                return ResourceManager.GetString("liB27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب دفع.
        /// </summary>
        internal static string liB28 {
            get {
                return ResourceManager.GetString("liB28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعدادات النظام.
        /// </summary>
        internal static string liB30 {
            get {
                return ResourceManager.GetString("liB30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطوط الرحلة.
        /// </summary>
        internal static string liB31 {
            get {
                return ResourceManager.GetString("liB31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسخ الاحتياطية.
        /// </summary>
        internal static string liB32 {
            get {
                return ResourceManager.GetString("liB32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحركة اليومية.
        /// </summary>
        internal static string liB41 {
            get {
                return ResourceManager.GetString("liB41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حركة الشاحنات.
        /// </summary>
        internal static string liB42 {
            get {
                return ResourceManager.GetString("liB42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الترحيل المعلقة.
        /// </summary>
        internal static string liB43 {
            get {
                return ResourceManager.GetString("liB43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الفواتير النقدية.
        /// </summary>
        internal static string liB44 {
            get {
                return ResourceManager.GetString("liB44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الفواتير الملغاة.
        /// </summary>
        internal static string liB45 {
            get {
                return ResourceManager.GetString("liB45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الفواتير الآجلة.
        /// </summary>
        internal static string liB46 {
            get {
                return ResourceManager.GetString("liB46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير لم يتم تحصيلها.
        /// </summary>
        internal static string liB47 {
            get {
                return ResourceManager.GetString("liB47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الفواتير المحصلة.
        /// </summary>
        internal static string liB48 {
            get {
                return ResourceManager.GetString("liB48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة تحصيل الفواتير.
        /// </summary>
        internal static string liB49 {
            get {
                return ResourceManager.GetString("liB49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان حركة شاحنة / سائق.
        /// </summary>
        internal static string liB50 {
            get {
                return ResourceManager.GetString("liB50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل أداء موظفي الفروع.
        /// </summary>
        internal static string liB51 {
            get {
                return ResourceManager.GetString("liB51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفصيلي أداء موظف فرع.
        /// </summary>
        internal static string liB52 {
            get {
                return ResourceManager.GetString("liB52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجمالي أنشطة العملاء.
        /// </summary>
        internal static string liB53 {
            get {
                return ResourceManager.GetString("liB53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراقبة تسلسل السندات.
        /// </summary>
        internal static string liB54 {
            get {
                return ResourceManager.GetString("liB54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصيانة.
        /// </summary>
        internal static string liC01 {
            get {
                return ResourceManager.GetString("liC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفنيين.
        /// </summary>
        internal static string liC30 {
            get {
                return ResourceManager.GetString("liC30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند استلام مستعمل.
        /// </summary>
        internal static string liC39 {
            get {
                return ResourceManager.GetString("liC39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشييك تسليم للتصليح.
        /// </summary>
        internal static string liC41 {
            get {
                return ResourceManager.GetString("liC41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشييك تسليم للاصلاح.
        /// </summary>
        internal static string liC43 {
            get {
                return ResourceManager.GetString("liC43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أجمالي مصروفات الشاحنات.
        /// </summary>
        internal static string liC61 {
            get {
                return ResourceManager.GetString("liC61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الشئون الإدارية.
        /// </summary>
        internal static string liD1 {
            get {
                return ResourceManager.GetString("liD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الرئيسية.
        /// </summary>
        internal static string liD10 {
            get {
                return ResourceManager.GetString("liD10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الرواتب.
        /// </summary>
        internal static string liD11 {
            get {
                return ResourceManager.GetString("liD11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاكواد العامة.
        /// </summary>
        internal static string liD12 {
            get {
                return ResourceManager.GetString("liD12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مؤثرات الرواتب.
        /// </summary>
        internal static string liD20 {
            get {
                return ResourceManager.GetString("liD20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإضافي.
        /// </summary>
        internal static string liD21 {
            get {
                return ResourceManager.GetString("liD21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلفه ماليه.
        /// </summary>
        internal static string liD22 {
            get {
                return ResourceManager.GetString("liD22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التشغيل الشهري.
        /// </summary>
        internal static string liD23 {
            get {
                return ResourceManager.GetString("liD23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوية إجازة موظف.
        /// </summary>
        internal static string liD24 {
            get {
                return ResourceManager.GetString("liD24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسوية خروج موظف.
        /// </summary>
        internal static string liD25 {
            get {
                return ResourceManager.GetString("liD25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعدادات النظام.
        /// </summary>
        internal static string liD30 {
            get {
                return ResourceManager.GetString("liD30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف الرواتب.
        /// </summary>
        internal static string liD40 {
            get {
                return ResourceManager.GetString("liD40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجازات الرسمية.
        /// </summary>
        internal static string lis49 {
            get {
                return ResourceManager.GetString("lis49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل دخول.
        /// </summary>
        internal static string LoginMsg {
            get {
                return ResourceManager.GetString("LoginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logoText.
        /// </summary>
        internal static string logoText {
            get {
                return ResourceManager.GetString("logoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot;fa fa-power-off&quot;&gt;&lt;/i&gt; خروج.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع الرئيسي.
        /// </summary>
        internal static string MainBranch {
            get {
                return ResourceManager.GetString("MainBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات الاساسية.
        /// </summary>
        internal static string MainData {
            get {
                return ResourceManager.GetString("MainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu lgray slide.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسالة.
        /// </summary>
        internal static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name1.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأخبار.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحباً بكم في نظام الناقلات البرية 2015.
        /// </summary>
        internal static string News1 {
            get {
                return ResourceManager.GetString("News1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام متطور يلبي أحتياجاتكم.
        /// </summary>
        internal static string News2 {
            get {
                return ResourceManager.GetString("News2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن دائما في خدمة عملائنا من خلال نظامنا في 24 ساعة طوال أيام الاسبوع.
        /// </summary>
        internal static string News3 {
            get {
                return ResourceManager.GetString("News3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحن دائما نواكب أحدث النظم لخدمة عملائنا.
        /// </summary>
        internal static string News4 {
            get {
                return ResourceManager.GetString("News4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يسعدنا تلقي اقتراحاتكم من خلال الاتصال على الدعم الفني.
        /// </summary>
        internal static string News5 {
            get {
                return ResourceManager.GetString("News5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميع الحقوق محفوظة &amp;copy; الناقلات البرية 2015.
        /// </summary>
        internal static string News6 {
            get {
                return ResourceManager.GetString("News6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خدمة جديدة.
        /// </summary>
        internal static string NewService {
            get {
                return ResourceManager.GetString("NewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد بيانات.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان تسليم شاحنة.
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان تحويل شاحنة.
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان أستلام شاحنة.
        /// </summary>
        internal static string Note3 {
            get {
                return ResourceManager.GetString("Note3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فتح في نافذة جديدة.
        /// </summary>
        internal static string OpenNewWindow {
            get {
                return ResourceManager.GetString("OpenNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p1.
        /// </summary>
        internal static string p {
            get {
                return ResourceManager.GetString("p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء حفظ البيانات الحالية و شكرا.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جرد البضاعة.
        /// </summary>
        internal static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جرد فعلي نهاية الفترة.
        /// </summary>
        internal static string R10 {
            get {
                return ResourceManager.GetString("R10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  حركة تفصيلية لصنف.
        /// </summary>
        internal static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام غير مرتبط بشراء.
        /// </summary>
        internal static string R3 {
            get {
                return ResourceManager.GetString("R3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب شراء بضاعة.
        /// </summary>
        internal static string S0 {
            get {
                return ResourceManager.GetString("S0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أمر شراء بضاعة.
        /// </summary>
        internal static string S1 {
            get {
                return ResourceManager.GetString("S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند تسوية.
        /// </summary>
        internal static string S10 {
            get {
                return ResourceManager.GetString("S10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة مشتريات.
        /// </summary>
        internal static string S2 {
            get {
                return ResourceManager.GetString("S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتجع مشتريات.
        /// </summary>
        internal static string S3 {
            get {
                return ResourceManager.GetString("S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أشعار أضافة.
        /// </summary>
        internal static string S4 {
            get {
                return ResourceManager.GetString("S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند صرف بضاعة.
        /// </summary>
        internal static string S5 {
            get {
                return ResourceManager.GetString("S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة صرف.
        /// </summary>
        internal static string S6 {
            get {
                return ResourceManager.GetString("S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب تحويل.
        /// </summary>
        internal static string S7 {
            get {
                return ResourceManager.GetString("S7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب دفع.
        /// </summary>
        internal static string S8 {
            get {
                return ResourceManager.GetString("S8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب شراء مواد.
        /// </summary>
        internal static string S9 {
            get {
                return ResourceManager.GetString("S9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرسل.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستعلام عن خدمة.
        /// </summary>
        internal static string ServiceInquery {
            get {
                return ResourceManager.GetString("ServiceInquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأعدادات.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المــوقع:.
        /// </summary>
        internal static string SiteLoc {
            get {
                return ResourceManager.GetString("SiteLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float: right;.
        /// </summary>
        internal static string StarPos {
            get {
                return ResourceManager.GetString("StarPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخزن.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستودع:.
        /// </summary>
        internal static string StoreLoc {
            get {
                return ResourceManager.GetString("StoreLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستودعات.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subnav.
        /// </summary>
        internal static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم تشغيل مطابقة الارصدة بنجاح.
        /// </summary>
        internal static string SuccessTally {
            get {
                return ResourceManager.GetString("SuccessTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم تحديث النظام اليوم الساعة.
        /// </summary>
        internal static string SysUpdate {
            get {
                return ResourceManager.GetString("SysUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعدادات النظام.
        /// </summary>
        internal static string T1 {
            get {
                return ResourceManager.GetString("T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقفال الفترة.
        /// </summary>
        internal static string T2 {
            get {
                return ResourceManager.GetString("T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم اختيار تشغيل نظام مطابقة الأرصدة.
        /// </summary>
        internal static string Tally {
            get {
                return ResourceManager.GetString("Tally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-align: right;.
        /// </summary>
        internal static string TextAlign {
            get {
                return ResourceManager.GetString("TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-align: left;.
        /// </summary>
        internal static string TextAlign2 {
            get {
                return ResourceManager.GetString("TextAlign2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعاملات.
        /// </summary>
        internal static string Transactions {
            get {
                return ResourceManager.GetString("Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رحلة.
        /// </summary>
        internal static string Trip {
            get {
                return ResourceManager.GetString("Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاهزة للترحيل إلى.
        /// </summary>
        internal static string TripReady {
            get {
                return ResourceManager.GetString("TripReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الشاحنات.
        /// </summary>
        internal static string TruckList {
            get {
                return ResourceManager.GetString("TruckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم:.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب أصلاح.
        /// </summary>
        internal static string W1 {
            get {
                return ResourceManager.GetString("W1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب شراء مواد.
        /// </summary>
        internal static string W10 {
            get {
                return ResourceManager.GetString("W10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أمر تشغيل.
        /// </summary>
        internal static string W2 {
            get {
                return ResourceManager.GetString("W2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كارت متابعة صيانة.
        /// </summary>
        internal static string W3 {
            get {
                return ResourceManager.GetString("W3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب صرف قطع غيار.
        /// </summary>
        internal static string W4 {
            get {
                return ResourceManager.GetString("W4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فحص رأس سيارة.
        /// </summary>
        internal static string W5 {
            get {
                return ResourceManager.GetString("W5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كارت تسليم مركبة.
        /// </summary>
        internal static string W6 {
            get {
                return ResourceManager.GetString("W6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كارت متابعة الإطارات.
        /// </summary>
        internal static string W7 {
            get {
                return ResourceManager.GetString("W7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متابعة إطارات شاحنة.
        /// </summary>
        internal static string W8 {
            get {
                return ResourceManager.GetString("W8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب دفع.
        /// </summary>
        internal static string W9 {
            get {
                return ResourceManager.GetString("W9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الورشه.
        /// </summary>
        internal static string WorkShop {
            get {
                return ResourceManager.GetString("WorkShop", resourceCulture);
            }
        }
    }
}
